### ISSUE TITLE
Error with nodejs example

### ISSUE THREAD

**Issue by ellis2323** [andipaetzold/mdb-reader#168]
I have this error with node 14.5 version:
```

file:///C:/Users/laure/Documents/Perso/Sources/live/node_modules/mdb-reader/lib/codec-handler/handlers/office/agile/EncryptionDescriptor.js:1
import { XMLParser } from "fast-xml-parser";
         ^^^^^^^^^
SyntaxError: The requested module 'fast-xml-parser' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'fast-xml-parser';
const { XMLParser } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
    at async formattedImport (C:\Users\laure\Documents\Perso\Sources\live\node_modules\mocha\lib\esm-utils.js:7:14)
    at async Object.exports.loadFilesAsync (C:\Users\laure\Documents\Perso\Sources\live\node_modules\mocha\lib\esm-utils.js:55:20)
    at async singleRun (C:\Users\laure\Documents\Perso\Sources\live\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (C:\Users\laure\Documents\Perso\Sources\live\node_modules\mocha\lib\cli\run.js:362:5)
```

It seems the problem comes with 'src/codec-handler/handlers/office/agile/EncryptionDescriptor.js' file.

Best regards,

**Comment by andipaetzold** [comment]
Hey :wave: 

I was able to reproduce your error. It looks like this import only works from node 14.13 and breaks with earlier versions.

I'll work on an update to make it work for earlier node versions as well.

**Comment by andipaetzold** [comment]
Version 2.1.1 should fix your issue. Feel free to reopen the issue if you still run into problems.
